/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CalculatorBox {
    }
    interface CalculatorButton {
    }
}
declare global {
    interface HTMLCalculatorBoxElement extends Components.CalculatorBox, HTMLStencilElement {
    }
    var HTMLCalculatorBoxElement: {
        prototype: HTMLCalculatorBoxElement;
        new (): HTMLCalculatorBoxElement;
    };
    interface HTMLCalculatorButtonElement extends Components.CalculatorButton, HTMLStencilElement {
    }
    var HTMLCalculatorButtonElement: {
        prototype: HTMLCalculatorButtonElement;
        new (): HTMLCalculatorButtonElement;
    };
    interface HTMLElementTagNameMap {
        "calculator-box": HTMLCalculatorBoxElement;
        "calculator-button": HTMLCalculatorButtonElement;
    }
}
declare namespace LocalJSX {
    interface CalculatorBox {
    }
    interface CalculatorButton {
    }
    interface IntrinsicElements {
        "calculator-box": CalculatorBox;
        "calculator-button": CalculatorButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "calculator-box": LocalJSX.CalculatorBox & JSXBase.HTMLAttributes<HTMLCalculatorBoxElement>;
            "calculator-button": LocalJSX.CalculatorButton & JSXBase.HTMLAttributes<HTMLCalculatorButtonElement>;
        }
    }
}
